// Auto-generated by `supabase gen types typescript`.
// Regenerate with: pnpm db:types
// Do not edit manually.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.1";
  };
  public: {
    Tables: {
      agent_activity_log: {
        Row: {
          activity_type: string;
          created_at: string | null;
          deal_id: string | null;
          id: string;
          message: string;
          metadata: Json | null;
          trader_id: string;
        };
        Insert: {
          activity_type: string;
          created_at?: string | null;
          deal_id?: string | null;
          id?: string;
          message: string;
          metadata?: Json | null;
          trader_id: string;
        };
        Update: {
          activity_type?: string;
          created_at?: string | null;
          deal_id?: string | null;
          id?: string;
          message?: string;
          metadata?: Json | null;
          trader_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "agent_activity_log_deal_id_fkey";
            columns: ["deal_id"];
            isOneToOne: false;
            referencedRelation: "deals";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "agent_activity_log_trader_id_fkey";
            columns: ["trader_id"];
            isOneToOne: false;
            referencedRelation: "traders";
            referencedColumns: ["id"];
          },
        ];
      };
      assets: {
        Row: {
          acquired_at: string;
          id: string;
          name: string;
          source_deal_id: string | null;
          source_outcome_id: string | null;
          trader_id: string;
          value_usdc: number;
        };
        Insert: {
          acquired_at?: string;
          id?: string;
          name: string;
          source_deal_id?: string | null;
          source_outcome_id?: string | null;
          trader_id: string;
          value_usdc?: number;
        };
        Update: {
          acquired_at?: string;
          id?: string;
          name?: string;
          source_deal_id?: string | null;
          source_outcome_id?: string | null;
          trader_id?: string;
          value_usdc?: number;
        };
        Relationships: [
          {
            foreignKeyName: "assets_source_deal_id_fkey";
            columns: ["source_deal_id"];
            isOneToOne: false;
            referencedRelation: "deals";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "assets_source_outcome_id_fkey";
            columns: ["source_outcome_id"];
            isOneToOne: false;
            referencedRelation: "deal_outcomes";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "assets_trader_id_fkey";
            columns: ["trader_id"];
            isOneToOne: false;
            referencedRelation: "traders";
            referencedColumns: ["id"];
          },
        ];
      };
      deal_approvals: {
        Row: {
          created_at: string | null;
          deal_id: string;
          desk_manager_id: string;
          entry_cost_usdc: number;
          expires_at: string;
          id: string;
          pot_usdc: number;
          resolved_at: string | null;
          status: string;
          trader_id: string;
        };
        Insert: {
          created_at?: string | null;
          deal_id: string;
          desk_manager_id: string;
          entry_cost_usdc: number;
          expires_at: string;
          id?: string;
          pot_usdc: number;
          resolved_at?: string | null;
          status?: string;
          trader_id: string;
        };
        Update: {
          created_at?: string | null;
          deal_id?: string;
          desk_manager_id?: string;
          entry_cost_usdc?: number;
          expires_at?: string;
          id?: string;
          pot_usdc?: number;
          resolved_at?: string | null;
          status?: string;
          trader_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "deal_approvals_deal_id_fkey";
            columns: ["deal_id"];
            isOneToOne: false;
            referencedRelation: "deals";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "deal_approvals_desk_manager_id_fkey";
            columns: ["desk_manager_id"];
            isOneToOne: false;
            referencedRelation: "desk_managers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "deal_approvals_trader_id_fkey";
            columns: ["trader_id"];
            isOneToOne: false;
            referencedRelation: "traders";
            referencedColumns: ["id"];
          },
        ];
      };
      deal_outcomes: {
        Row: {
          assets_gained: Json;
          assets_lost: Json;
          created_at: string;
          deal_id: string;
          id: string;
          narrative: Json;
          on_chain_tx_hash: string | null;
          pot_change_usdc: number;
          rake_usdc: number;
          trader_id: string;
          trader_pnl_usdc: number;
          trader_wiped_out: boolean;
          wipeout_reason: string | null;
        };
        Insert: {
          assets_gained?: Json;
          assets_lost?: Json;
          created_at?: string;
          deal_id: string;
          id?: string;
          narrative?: Json;
          on_chain_tx_hash?: string | null;
          pot_change_usdc?: number;
          rake_usdc?: number;
          trader_id: string;
          trader_pnl_usdc?: number;
          trader_wiped_out?: boolean;
          wipeout_reason?: string | null;
        };
        Update: {
          assets_gained?: Json;
          assets_lost?: Json;
          created_at?: string;
          deal_id?: string;
          id?: string;
          narrative?: Json;
          on_chain_tx_hash?: string | null;
          pot_change_usdc?: number;
          rake_usdc?: number;
          trader_id?: string;
          trader_pnl_usdc?: number;
          trader_wiped_out?: boolean;
          wipeout_reason?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "deal_outcomes_deal_id_fkey";
            columns: ["deal_id"];
            isOneToOne: false;
            referencedRelation: "deals";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "deal_outcomes_trader_id_fkey";
            columns: ["trader_id"];
            isOneToOne: false;
            referencedRelation: "traders";
            referencedColumns: ["id"];
          },
        ];
      };
      deals: {
        Row: {
          created_at: string;
          creator_address: string | null;
          creator_id: string | null;
          creator_type: string;
          entry_cost_usdc: number;
          entry_count: number;
          fee_usdc: number | null;
          id: string;
          max_extraction_percentage: number;
          on_chain_deal_id: number | null;
          on_chain_tx_hash: string | null;
          pot_usdc: number;
          prompt: string;
          source_headline: string | null;
          status: string;
          updated_at: string;
          wipeout_count: number;
        };
        Insert: {
          created_at?: string;
          creator_address?: string | null;
          creator_id?: string | null;
          creator_type: string;
          entry_cost_usdc: number;
          entry_count?: number;
          fee_usdc?: number | null;
          id?: string;
          max_extraction_percentage?: number;
          on_chain_deal_id?: number | null;
          on_chain_tx_hash?: string | null;
          pot_usdc: number;
          prompt: string;
          source_headline?: string | null;
          status?: string;
          updated_at?: string;
          wipeout_count?: number;
        };
        Update: {
          created_at?: string;
          creator_address?: string | null;
          creator_id?: string | null;
          creator_type?: string;
          entry_cost_usdc?: number;
          entry_count?: number;
          fee_usdc?: number | null;
          id?: string;
          max_extraction_percentage?: number;
          on_chain_deal_id?: number | null;
          on_chain_tx_hash?: string | null;
          pot_usdc?: number;
          prompt?: string;
          source_headline?: string | null;
          status?: string;
          updated_at?: string;
          wipeout_count?: number;
        };
        Relationships: [
          {
            foreignKeyName: "deals_creator_id_fkey";
            columns: ["creator_id"];
            isOneToOne: false;
            referencedRelation: "desk_managers";
            referencedColumns: ["id"];
          },
        ];
      };
      desk_managers: {
        Row: {
          created_at: string;
          display_name: string | null;
          id: string;
          settings: Json;
          updated_at: string;
          wallet_address: string;
        };
        Insert: {
          created_at?: string;
          display_name?: string | null;
          id?: string;
          settings?: Json;
          updated_at?: string;
          wallet_address: string;
        };
        Update: {
          created_at?: string;
          display_name?: string | null;
          id?: string;
          settings?: Json;
          updated_at?: string;
          wallet_address?: string;
        };
        Relationships: [];
      };
      market_narratives: {
        Row: {
          created_at: string | null;
          epoch: number;
          events_ingested: Json;
          headlines: Json;
          id: string;
          raw_narrative: string;
          world_state: Json;
        };
        Insert: {
          created_at?: string | null;
          epoch: number;
          events_ingested?: Json;
          headlines: Json;
          id?: string;
          raw_narrative: string;
          world_state: Json;
        };
        Update: {
          created_at?: string | null;
          epoch?: number;
          events_ingested?: Json;
          headlines?: Json;
          id?: string;
          raw_narrative?: string;
          world_state?: Json;
        };
        Relationships: [];
      };
      siwa_nonces: {
        Row: {
          created_at: string;
          expires_at: string;
          nonce: string;
        };
        Insert: {
          created_at?: string;
          expires_at: string;
          nonce: string;
        };
        Update: {
          created_at?: string;
          expires_at?: string;
          nonce?: string;
        };
        Relationships: [];
      };
      system_prompts: {
        Row: {
          content: string;
          created_at: string;
          id: string;
          is_active: boolean;
          name: string;
          return_format: string | null;
          updated_at: string;
        };
        Insert: {
          content: string;
          created_at?: string;
          id?: string;
          is_active?: boolean;
          name: string;
          return_format?: string | null;
          updated_at?: string;
        };
        Update: {
          content?: string;
          created_at?: string;
          id?: string;
          is_active?: boolean;
          name?: string;
          return_format?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      trader_transactions: {
        Row: {
          amount_usdc: number | null;
          block_number: number | null;
          created_at: string;
          deal_id: string | null;
          id: string;
          on_chain_deal_id: number | null;
          pnl_usdc: number | null;
          rake_usdc: number | null;
          trader_id: string;
          tx_hash: string;
          type: string;
        };
        Insert: {
          amount_usdc?: number | null;
          block_number?: number | null;
          created_at?: string;
          deal_id?: string | null;
          id?: string;
          on_chain_deal_id?: number | null;
          pnl_usdc?: number | null;
          rake_usdc?: number | null;
          trader_id: string;
          tx_hash: string;
          type: string;
        };
        Update: {
          amount_usdc?: number | null;
          block_number?: number | null;
          created_at?: string;
          deal_id?: string | null;
          id?: string;
          on_chain_deal_id?: number | null;
          pnl_usdc?: number | null;
          rake_usdc?: number | null;
          trader_id?: string;
          tx_hash?: string;
          type?: string;
        };
        Relationships: [
          {
            foreignKeyName: "trader_transactions_deal_id_fkey";
            columns: ["deal_id"];
            isOneToOne: false;
            referencedRelation: "deals";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "trader_transactions_trader_id_fkey";
            columns: ["trader_id"];
            isOneToOne: false;
            referencedRelation: "traders";
            referencedColumns: ["id"];
          },
        ];
      };
      traders: {
        Row: {
          cdp_account_name: string | null;
          cdp_owner_address: string | null;
          cdp_wallet_address: string | null;
          created_at: string;
          escrow_balance_usdc: number | null;
          id: string;
          last_cycle_at: string | null;
          mandate: Json;
          name: string;
          owner_address: string;
          status: string;
          tba_address: string | null;
          token_id: number;
          updated_at: string;
        };
        Insert: {
          cdp_account_name?: string | null;
          cdp_owner_address?: string | null;
          cdp_wallet_address?: string | null;
          created_at?: string;
          escrow_balance_usdc?: number | null;
          id?: string;
          last_cycle_at?: string | null;
          mandate?: Json;
          name: string;
          owner_address: string;
          status?: string;
          tba_address?: string | null;
          token_id: number;
          updated_at?: string;
        };
        Update: {
          cdp_account_name?: string | null;
          cdp_owner_address?: string | null;
          cdp_wallet_address?: string | null;
          created_at?: string;
          escrow_balance_usdc?: number | null;
          id?: string;
          last_cycle_at?: string | null;
          mandate?: Json;
          name?: string;
          owner_address?: string;
          status?: string;
          tba_address?: string | null;
          token_id?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<
  keyof Database,
  "public"
>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
