/**
 * Next.js re-exports of legacy Base Sepolia deal-game constants (#262).
 */
export {
  ACTIVE_BASE_SEPOLIA_DEPLOYMENT,
  BASE_SEPOLIA_CAIP2,
  BASE_SEPOLIA_CHAIN_ID,
  BASE_SEPOLIA_SLUG,
  ERC6551_DEFAULT_IMPLEMENTATION,
  ERC6551_REGISTRY_ADDRESS,
  FORBIDDEN_MAINNET_CHAIN_ID,
  FORBIDDEN_MAINNET_USDC,
  IDENTITY_REGISTRY_ADDRESS,
  LEGACY_BASE_SEPOLIA_RECOMMEND_WAIT_BLOCKS,
  LEGACY_SEAT_VAULT_CONFIRMATION_DEPTH,
  REPUTATION_REGISTRY_ADDRESS,
  USDC_SEPOLIA_ADDRESS,
  baseSepoliaChain,
  isBaseSepoliaChainId,
  requireBaseSepoliaRpcUrl,
  type ActiveBaseSepoliaDeployment,
} from "../../../convex/lib/legacy";
